### ISSUE TITLE
Allow toy description to contain HTML

### ISSUE THREAD

**Issue by hchris28** [toy-yo/src#27]
Can we use $sce to allow html content in toy descriptions?

**Comment by sharathudupa** [comment]
Yeah, you can store whatever you want. How will admin enter this content though?

Sent from Outlook




On Fri, Apr 1, 2016 at 6:30 AM -0700, "Chris Haskins" <notifications@github.com> wrote:





Can we use $sce to allow html content in toy descriptions?

---
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub:
https://github.com/toy-yo/src/issues/27

**Comment by hchris28** [comment]
Storing the data isn't the problem, html-decoding it on output is. ng-bind-html, which is used to html-decode in the view, throws an error unless the content is marked as trusted by $sce. We might also consider using markdown, but trusting the html is the short-term fix. 

For now, html will be entered as text. In future we can implement a simple html editor.

**Comment by sharathudupa** [comment]
Ok so are you using the $sce?
